<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<AppDesignerFolder>Properties</AppDesignerFolder>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
		<PackageReference Include="PDFsharp-MigraDoc-WPF" Version="6.2.4" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
		<PackageReference Include="System.Management" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Branding\WeberIT-Logo.png" />

		<Content Include="Resources\Branding\WeberIT-Logo.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>